defaults:
  - env/behavior_r1pro@env.train
  - env/behavior_r1pro@env.eval
  - model/openvla_oft@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 0
    rollout: 0-3
    env: 4-7

runner:
  task_type: embodied
  rollout_only: true
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_openvla_rollout_only"
    logger_backends: ["tensorboard"]

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  eval_policy_path: null
  val_check_interval: -1
  save_interval: -1
  seq_length: 4096
  max_prompt_length: 50

  resume_dir: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 1
  rollout_epoch: 8
  eval_rollout_epoch: 1

  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

  train:
    total_num_envs: 4
    max_episode_steps: 3000
    max_steps_per_rollout_epoch: 3000
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/rollout
  eval:
    total_num_envs: 4
    max_episode_steps: 3000
    max_steps_per_rollout_epoch: 3000
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  save_rollout_only: true
  save_rollout:
    enabled: true
    every_n_steps: 1
    dir: "/data1/heyelin/rlinf/RLinf-main/offline_rollouts"
  offline:
    dir: null
    loop: true
    strict: true
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 1

  model:
    model_path: "/data1/heyelin/rlinf/RLinf-main/behavior_rlinf_openvlaoft/"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  micro_batch_size: 4
  global_batch_size: 16
  seed: 1234
  enable_offload: True

  model:
    model_path: "/data1/heyelin/rlinf/RLinf-main/behavior_rlinf_openvlaoft/"
    model_type: "openvla_oft"
    value_type: ${algorithm.reward_type}
    action_dim: 23
    unnorm_key: behavior_turn_on_radio
    add_value_head: True
    num_images_in_input: 3

  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0
    weight_decay: 0.01
    critic_warmup_steps: 0

  tokenizer:
    tokenizer_type: "HuggingFaceTokenizer"
    tokenizer_model: "/data1/heyelin/rlinf/RLinf-main/behavior_rlinf_openvlaoft/"
    use_fast: False
    trust_remote_code: True
    padding_side: "right"

  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
